/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulasiUnitIdRouteImport } from './routes/simulasi.$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulasiUnitIdRoute = SimulasiUnitIdRouteImport.update({
  id: '/simulasi/$unitId',
  path: '/simulasi/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/simulasi/$unitId': typeof SimulasiUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/simulasi/$unitId': typeof SimulasiUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/simulasi/$unitId': typeof SimulasiUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/simulasi/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/simulasi/$unitId'
  id: '__root__' | '/' | '/simulasi/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimulasiUnitIdRoute: typeof SimulasiUnitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulasi/$unitId': {
      id: '/simulasi/$unitId'
      path: '/simulasi/$unitId'
      fullPath: '/simulasi/$unitId'
      preLoaderRoute: typeof SimulasiUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimulasiUnitIdRoute: SimulasiUnitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
