/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanduanIndexRouteImport } from './routes/panduan.index'
import { Route as SimulasiUnitIdRouteImport } from './routes/simulasi.$unitId'
import { Route as PanduanUnitIdRouteImport } from './routes/panduan.$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanIndexRoute = PanduanIndexRouteImport.update({
  id: '/panduan/',
  path: '/panduan/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulasiUnitIdRoute = SimulasiUnitIdRouteImport.update({
  id: '/simulasi/$unitId',
  path: '/simulasi/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanUnitIdRoute = PanduanUnitIdRouteImport.update({
  id: '/panduan/$unitId',
  path: '/panduan/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panduan/$unitId': typeof PanduanUnitIdRoute
  '/simulasi/$unitId': typeof SimulasiUnitIdRoute
  '/panduan/': typeof PanduanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panduan/$unitId': typeof PanduanUnitIdRoute
  '/simulasi/$unitId': typeof SimulasiUnitIdRoute
  '/panduan': typeof PanduanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panduan/$unitId': typeof PanduanUnitIdRoute
  '/simulasi/$unitId': typeof SimulasiUnitIdRoute
  '/panduan/': typeof PanduanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/panduan/$unitId' | '/simulasi/$unitId' | '/panduan/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/panduan/$unitId' | '/simulasi/$unitId' | '/panduan'
  id: '__root__' | '/' | '/panduan/$unitId' | '/simulasi/$unitId' | '/panduan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanduanUnitIdRoute: typeof PanduanUnitIdRoute
  SimulasiUnitIdRoute: typeof SimulasiUnitIdRoute
  PanduanIndexRoute: typeof PanduanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan/': {
      id: '/panduan/'
      path: '/panduan'
      fullPath: '/panduan/'
      preLoaderRoute: typeof PanduanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulasi/$unitId': {
      id: '/simulasi/$unitId'
      path: '/simulasi/$unitId'
      fullPath: '/simulasi/$unitId'
      preLoaderRoute: typeof SimulasiUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan/$unitId': {
      id: '/panduan/$unitId'
      path: '/panduan/$unitId'
      fullPath: '/panduan/$unitId'
      preLoaderRoute: typeof PanduanUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanduanUnitIdRoute: PanduanUnitIdRoute,
  SimulasiUnitIdRoute: SimulasiUnitIdRoute,
  PanduanIndexRoute: PanduanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
